package corba;


/**
* corba/ServiceCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from twitter.idl
* jeudi 7 juin 2018 15 h 11 CEST
*/

public interface ServiceCorbaOperations 
{
  String getUsers ();
  void createNewUser (String u);
  String isUserPasswordCorrect (String u);
  void removeUser (String u);
  String[] getUsersFollowing (String u);
  String[] getUsersFollowedBy (String u);
  void startFollowing (String follower, String followed);
  void stopFollowing (String follower, String followed);
  void createNewTweet (String username, String t);
  String[] getTweetsOfUser (String username);
} // interface ServiceCorbaOperations
