package corba;


/**
* corba/ServiceCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from twitter.idl
* mercredi 20 juin 2018 21 h 28 CEST
*/

public interface ServiceCorbaOperations 
{
  String[] getUsers ();
  String createNewUser (String username, String password);
  String isUserPasswordCorrect (String username, String password);
  void removeUser (String u);
  String[] getUsersFollowing (String u);
  String[] getUsersFollowedBy (String u);
  void startFollowing (String follower, String followed);
  void stopFollowing (String follower, String followed);
  void createNewTweet (String username, String t);
  String[] getTweetsOfUser (String username);
} // interface ServiceCorbaOperations
