package corba;


/**
* corba/ServiceCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from twitter.idl
* mercredi 20 juin 2018 21 h 28 CEST
*/

public interface ServiceCorba extends ServiceCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceCorba
