package corba;


/**
* corba/TweetsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from twitter.idl
* jeudi 7 juin 2018 16 h 21 CEST
*/

public final class TweetsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public TweetsHolder ()
  {
  }

  public TweetsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.TweetsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.TweetsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.TweetsHelper.type ();
  }

}
